### PR TITLE
Deleted PurePursuit package and resolve gitignore issues

### PR DESCRIPTION
**Pull request by richiksc**

### CODE REVIEW

**Review by pdeutsch — APPROVED** [review]

**Review by richiksc — COMMENTED** [review]
Ok. Understood. In FTC we all used android studio/intellij so it was recommended that we do include IML files in the repo as to make sure everyone's project is configured with the same modules, J/SDK etc. If you do delete the IML I recommend adding it to the .gitignore. Ignoring file extensions is done via `*.ext` not just `.ext` as you had before. `.ext` matches files that are literally called `.ext`.

**Comment by andrewfhou** [comment]
I hate managing the gitignore so much

**Review by andrewfhou — APPROVED** [review]
Looks good

edit: of course I was added to the rookie team. Requesting review from everyone else manually

**Comment by richiksc** [comment]
Why'd you assign everybody. There is a difference between assignment and requesting review.

**Comment by andrewfhou** [comment]
Because mobile is a pain in the ass and I hit the wrong button

**Comment by richiksc** [comment]
I've cleaned up the commit history. Can I merge these changes?

**Comment by richiksc** [comment]
Authorized by @eku952.

**Pull request merged**
